
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COR_CERRAR = 58;
  public static final int COR_ABRIR = 57;
  public static final int MULT = 24;
  public static final int CHAR = 6;
  public static final int FIND = 65;
  public static final int REMOVE = 60;
  public static final int UMINUS = 50;
  public static final int ENTERO = 17;
  public static final int CASE = 47;
  public static final int XOR = 38;
  public static final int DIFERENTE = 31;
  public static final int DOUBLE = 4;
  public static final int DOS_PUNTOS = 45;
  public static final int CONTINUE = 14;
  public static final int INT = 3;
  public static final int FOR = 11;
  public static final int NOT = 39;
  public static final int AND = 36;
  public static final int IDENTIFICADOR = 21;
  public static final int APPEND = 59;
  public static final int IGUAL = 30;
  public static final int CARACTER = 19;
  public static final int OR = 37;
  public static final int BOOL = 5;
  public static final int DIV = 25;
  public static final int INCREMENTO = 28;
  public static final int IF = 8;
  public static final int PUNTO_COMA = 44;
  public static final int EOF = 0;
  public static final int DECIMAL = 18;
  public static final int RETURN = 56;
  public static final int ASIG = 49;
  public static final int PAR_ABRIR = 40;
  public static final int NEW = 62;
  public static final int DECREMENTO = 29;
  public static final int error = 1;
  public static final int COMA = 51;
  public static final int CADENA = 16;
  public static final int MODULO = 27;
  public static final int MENOS = 23;
  public static final int MENOR = 32;
  public static final int START = 52;
  public static final int TOSTRING = 55;
  public static final int BREAK = 13;
  public static final int VOID = 53;
  public static final int SWITCH = 46;
  public static final int MAYOR = 34;
  public static final int POTENCIA = 26;
  public static final int LLAVE_CERRAR = 43;
  public static final int ELSE = 9;
  public static final int PUNTO = 63;
  public static final int LLAVE_ABRIR = 42;
  public static final int PAR_CERRAR = 41;
  public static final int WHILE = 10;
  public static final int LIST = 61;
  public static final int DEFAULT = 48;
  public static final int MAYOR_IGUAL = 35;
  public static final int STRINGTYPE = 7;
  public static final int BOOLEANO = 20;
  public static final int MENOR_IGUAL = 33;
  public static final int VAR = 2;
  public static final int LENGTH = 64;
  public static final int ROUND = 54;
  public static final int PRINT = 15;
  public static final int DO = 12;
  public static final int MAS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRINGTYPE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "CONTINUE",
  "PRINT",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "BOOLEANO",
  "IDENTIFICADOR",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "POTENCIA",
  "MODULO",
  "INCREMENTO",
  "DECREMENTO",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MENOR_IGUAL",
  "MAYOR",
  "MAYOR_IGUAL",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "PAR_ABRIR",
  "PAR_CERRAR",
  "LLAVE_ABRIR",
  "LLAVE_CERRAR",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "ASIG",
  "UMINUS",
  "COMA",
  "START",
  "VOID",
  "ROUND",
  "TOSTRING",
  "RETURN",
  "COR_ABRIR",
  "COR_CERRAR",
  "APPEND",
  "REMOVE",
  "LIST",
  "NEW",
  "PUNTO",
  "LENGTH",
  "FIND"
  };
}

