/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1_vd25_202400860;

import Abstracto.Instruccion;
import Simbolo.Arbol;
import Simbolo.TablaSimbolos;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.LinkedList;
import analisis.scanner;
import analisis.parser;
import Errores.Errores;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import Simbolo.Simbolo;

/**
 *
 * @author Christoper
 */
public class Interprete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interprete.class.getName());

    /**
     * Creates new form Interprete
     */
    public Interprete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Interpretar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("Interpretando...");
    try {
        String texto = jTextArea1.getText();
        scanner s = new scanner(new BufferedReader(new StringReader(texto)));
        parser p = new parser(s);

        // Paso 1: Análisis léxico
        if (!s.listaErrores.isEmpty()) {
            jTextArea2.setText(generarReporteErrores(s.listaErrores));
            return;
        }

        // Paso 2: Análisis sintáctico
        var resultado = p.parse();
        if (!p.listaErrores.isEmpty()) {
            jTextArea2.setText(generarReporteErrores(p.listaErrores));
            return;
        }

        // Paso 3: Validar si hay instrucciones
        if (!(resultado.value instanceof LinkedList)) {
            jTextArea2.setText("ERROR INTERNO: El parser no devolvió una lista.");
            return;
        }
        
        var ast = new Arbol((LinkedList<Instruccion>) resultado.value);
        var tabla = new TablaSimbolos();
        tabla.setNombre("GLOBAL");
        ast.setConsolas("");

        // Lista para acumular errores semánticos
        List<Errores> erroresSemantico = new ArrayList<>();

        for (var a : ast.getInstrucciones()) {
            Object res = a.interpretar(ast, tabla);
            if (res instanceof Errores) {
                erroresSemantico.add((Errores) res);
            }
        }

        // Si hay errores semánticos, mostrarlos
        if (!erroresSemantico.isEmpty()) {
            jTextArea2.setText(generarReporteErrores(erroresSemantico));
            return;
        }
        
        // Paso 5: Generar reportes combinados
        String salida = ast.getConsolas();
        List<Simbolo> simbolos = obtenerTodosLosSimbolos(tabla);
        String reporteSimbolos = generarReporteSimbolos(simbolos);

        jTextArea2.setText(
            "=== SALIDA ===\n" +
            (salida.isEmpty() ? "(sin salida)\n" : salida + "\n") +
            "\n=== TABLA DE SÍMBOLOS ===\n" +
            reporteSimbolos
        );
        
        } catch (Exception ex) {
        StringWriter sw = new StringWriter();
        ex.printStackTrace(new java.io.PrintWriter(sw));
        jTextArea2.setText("EXCEPCIÓN:\n" + sw);
        
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Método para generar el reporte de errores en formato tabular
private String generarReporteErrores(List<Errores> errores) {
    StringBuilder sb = new StringBuilder();
    sb.append(String.format("%-4s %-12s %-50s %-6s %-7s%n", "#", "TIPO", "DESCRIPCIÓN", "LÍNEA", "COLUMNA"));
    sb.append("----------------------------------------------------------------------------------\n");
    for (int i = 0; i < errores.size(); i++) {
        Errores e = errores.get(i);
        sb.append(String.format("%-4d %-12s %-50s %-6d %-7d%n",
            i + 1,
            e.getTipo(),
            e.getDesc(),
            e.getLinea(),
            e.getColumna()
        ));
    }
    return sb.toString();
}

// Método para recolectar todos los símbolos (incluyendo ámbitos anidados)
private List<Simbolo> obtenerTodosLosSimbolos(TablaSimbolos tabla) {
    List<Simbolo> simbolos = new ArrayList<>();
    Set<String> idsVistos = new HashSet<>(); // para evitar duplicados (mantiene el más local)

    TablaSimbolos actual = tabla;
    while (actual != null) {
        // Recorremos de la tabla más local a la global
        for (Simbolo s : actual.getTablaActual().values()) {
            if (!idsVistos.contains(s.getId().toLowerCase())) {
                simbolos.add(s);
                idsVistos.add(s.getId().toLowerCase());
            }
        }
        actual = actual.getTablaAnterior();
    }
    return simbolos;
}

// Método para generar el reporte de tabla de símbolos (Fase 1)
private String generarReporteSimbolos(List<Simbolo> simbolos) {
    StringBuilder sb = new StringBuilder();
     sb.append(String.format("%-4s %-15s %-15s %-20s %-6s %-7s%n", "#", "ID", "TIPO", "VALOR", "LÍNEA", "COLUMNA"));
    sb.append("------------------------------------------------------------------------\n");
    for (int i = 0; i < simbolos.size(); i++) {
        Simbolo s = simbolos.get(i);
        String tipoStr = "desconocido";
        if (s.getTipo() != null && s.getTipo().getTipo() != null) {
            tipoStr = s.getTipo().getTipo().name(); // Ej: ENTERO, CADENA, etc.
        }
        String valorStr = (s.getValor() != null) ? s.getValor().toString() : "null";
        sb.append(String.format("%-4d %-15s %-15s %-20s %-6d %-7d%n",
            i + 1,
            s.getId(),
            tipoStr,
            valorStr,
            s.getLinea(),
            s.getColumna()
        ));
    }
    return sb.toString();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interprete().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
