/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1_vd25_202400860;

import Abstracto.Instruccion;
import Simbolo.Arbol;
import Simbolo.TablaSimbolos;
import java.io.BufferedReader;
import java.io.StringReader;
import java.util.LinkedList;
import analisis.scanner;
import analisis.parser;
import Errores.Errores;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import Simbolo.Simbolo;
import Instruccion.Metodo;
import Instruccion.Start;
import Instruccion.Declaracion;
import Instruccion.Asignacion;
import Instruccion.Funcion;
import Instruccion.DeclaracionVector;
import Expresiones.DeclaracionLista;
import Instruccion.Llamada;
import java.awt.Desktop;
import java.awt.Image;
import java.io.IOException;
import java.io.File;
import java.io.FileWriter;
import java.io.InputStreamReader;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Christoper
 */
public class Interprete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interprete.class.getName());

    /**
     * Creates new form Interprete
     */
    public Interprete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton1.setText("Interpretar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jMenu4.setText("File");

        jMenuItem2.setText("Nuevo");
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Cargar");
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu5.setText("Limpiar");

        jMenuItem5.setText("Limpiar");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu5.add(jMenuItem5);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         jTextArea2.setText("Interpretando...\n");

        try {
            String texto = jTextArea1.getText();

            scanner s = new scanner(new BufferedReader(new StringReader(texto)));
            parser p = new parser(s);

            // =================== PARSE ===================
            var resultado = p.parse();

            LinkedList<Errores> errores = new LinkedList<>();
            errores.addAll(s.listaErrores);
            errores.addAll(p.listaErrores);

            if (!errores.isEmpty()) {
                jTextArea2.setText(generarReporteErrores(errores));
                return;
            }

            if (!(resultado.value instanceof LinkedList)) {
                jTextArea2.setText("ERROR INTERNO: El parser no devolvió instrucciones.");
                return;
            }

            // =================== AST y TABLA ===================
            Arbol ast = new Arbol((LinkedList<Instruccion>) resultado.value);
            TablaSimbolos tabla = new TablaSimbolos();
            tabla.setNombre("GLOBAL");
            ast.setConsolas("");
            ast.setTablaGlobal(tabla);


/// =================== 2️⃣ INTERPRETAR INSTRUCCIONES GLOBALES ===================
// =================== 2️⃣ REGISTRAR FUNCIONES Y VARIABLES GLOBALES ===================
for (var inst : ast.getInstrucciones()) {
    if (inst == null) continue;
    if (inst instanceof Start) continue; // Solo omitimos Start

    Object res = inst.interpretar(ast, tabla);
    if (res instanceof Errores e) {
        errores.add(e);
    }
}

            // =================== 3️⃣ BUSCAR START ===================
            Start start = null;
for (var inst : ast.getInstrucciones()) {
    if (inst instanceof Start srt) {
        start = srt;
        break;
    }
}

if (start != null) {
    // Ejecutar start SOLO si existe
    String nombreMain = start.getId();
    // Ahora:
Llamada llamadaMain = new Llamada(nombreMain, start.getParametros(), 0, 0);
    Object res = llamadaMain.interpretar(ast, tabla);
    if (res instanceof Errores e) {
        errores.add(e);
    }
}

            // =================== ERRORES ===================
            if (!errores.isEmpty()) {
                jTextArea2.setText(generarReporteErrores(errores));
                return;
            }

            // =================== SALIDA ===================
             String salida = ast.getConsolas();
        List<SimboloConEntorno> simbolos = obtenerTodosLosSimbolosConEntorno(ast);
        String astDot = ast.generarDOT();

        StringBuilder salidaFinal = new StringBuilder();
        salidaFinal.append("=== SALIDA ===\n");
        salidaFinal.append(salida.isEmpty() ? "(sin salida)\n" : salida + "\n");
        salidaFinal.append("\n=== TABLA DE SÍMBOLOS ===\n");
        salidaFinal.append(generarReporteSimbolos(simbolos));
        generarYMostrarPNG();

        jTextArea2.setText(salidaFinal.toString());
        
         try {
            File dotFile = new File("ast.dot");
            try (FileWriter fw = new FileWriter(dotFile)) {
                fw.write(astDot);
            }
            jTextArea2.append("\n\nAST guardado en: " + dotFile.getAbsolutePath());
        } catch (IOException e) {
            jTextArea2.append("\nNo se pudo guardar el archivo AST: " + e.getMessage());
        }
            
            

        } catch (Exception ex) {
            StringWriter sw = new StringWriter();
            ex.printStackTrace(new java.io.PrintWriter(sw));
            jTextArea2.setText("EXCEPCIÓN:\n" + sw);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText("");
        jTextArea1.setText("");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    
    private String valorToString(Object valor) {
    if (valor == null) return "null";

    // Listas dinámicas (java.util.List)
    if (valor instanceof java.util.List) {
        java.util.List<?> list = (java.util.List<?>) valor;
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < list.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append(valorToString(list.get(i))); // recursivo para listas de listas
        }
        sb.append("]");
        return sb.toString();
    }

    // Arreglo 1D (Object[])
    if (valor instanceof Object[]) {
        return java.util.Arrays.toString((Object[]) valor);
    }

    // Arreglo 2D (Object[][])
    if (valor instanceof Object[][]) {
        return java.util.Arrays.deepToString((Object[][]) valor);
    }

    // Valores simples: enteros, doubles, booleanos, chars, strings
    return valor.toString();
}
    
    // Método para generar el reporte de errores en formato tabular
private String generarReporteErrores(List<Errores> errores) {
    StringBuilder sb = new StringBuilder();
    sb.append(String.format("%-4s %-12s %-50s %-6s %-7s%n", "#", "TIPO", "DESCRIPCIÓN", "LÍNEA", "COLUMNA"));
    sb.append("----------------------------------------------------------------------------------\n");
    for (int i = 0; i < errores.size(); i++) {
        Errores e = errores.get(i);
        sb.append(String.format("%-4d %-12s %-50s %-6d %-7d%n",
            i + 1,
            e.getTipo(),
            e.getDesc(),
            e.getLinea(),
            e.getColumna()
        ));
    }
    return sb.toString();
}

private List<SimboloConEntorno> obtenerTodosLosSimbolosConEntorno(Arbol arbol) {
    List<SimboloConEntorno> simbolos = new ArrayList<>();
    Set<String> idsVistos = new HashSet<>();

    // Recorrer TODAS las tablas registradas
    for (TablaSimbolos tabla : arbol.getTodasLasTablas()) {
        String entorno = tabla.getNombre() != null ? tabla.getNombre() : "Global";
        for (Simbolo s : tabla.getTablaActual().values()) {
            // Evitar duplicados: mantener el más local (último encontrado)
            if (!idsVistos.contains(s.getId().toLowerCase())) {
                simbolos.add(new SimboloConEntorno(s, entorno));
                idsVistos.add(s.getId().toLowerCase());
            }
        }
    }
    return simbolos;
}

// Clase auxiliar (puedes ponerla dentro de Interprete como static)
private static class SimboloConEntorno {
    Simbolo simbolo;
    String entorno;
    SimboloConEntorno(Simbolo s, String e) { simbolo = s; entorno = e; }
}

private String generarReporteSimbolos(List<SimboloConEntorno> simbolos) {
    StringBuilder sb = new StringBuilder();
    sb.append(String.format("%-4s %-15s %-15s %-20s %-15s %-6s %-7s%n",
        "#", "ID", "TIPO", "VALOR", "ENTORNO", "LÍNEA", "COLUMNA"));
    sb.append("----------------------------------------------------------------------------------\n");
    
    for (int i = 0; i < simbolos.size(); i++) {
        SimboloConEntorno se = simbolos.get(i);
        Simbolo s = se.simbolo;
        String tipoStr = "desconocido";
        if (s.getTipo() != null && s.getTipo().getTipo() != null) {
            tipoStr = s.getTipo().getTipo().name();
        }
        String valorStr = valorToString(s.getValor());
        if (valorStr.length() > 20) valorStr = valorStr.substring(0, 17) + "...";
        String entorno = se.entorno;
        String entornoFinal = "Global";
        if (entorno != null && !entorno.equals("Global") && !entorno.equals("GLOBAL")) {
            entornoFinal = "Local";
        }

        sb.append(String.format("%-4d %-15s %-15s %-20s %-15s %-6d %-7d%n",
            i + 1,
            s.getId(),
            tipoStr,
            valorStr,
            entornoFinal,
            s.getLinea(),
            s.getColumna()
        ));
    }
    return sb.toString();
}

private void generarYMostrarPNG() {
    try {
        File dotFile = new File("ast.dot");
        if (!dotFile.exists()) {
            jTextArea2.append("\nNo se encontró ast.dot para generar la imagen.");
            return;
        }

        File pngFile = new File("ast.png");
        ProcessBuilder pb = new ProcessBuilder("dot", "-Tpng", dotFile.getAbsolutePath(), "-o", pngFile.getAbsolutePath());
        Process process = pb.start();
        int exitCode = process.waitFor();

        if (exitCode != 0) {
            try (var br = new BufferedReader(new InputStreamReader(process.getErrorStream()))) {
                String err = br.lines().collect(java.util.stream.Collectors.joining("\n"));
                jTextArea2.append("\nError Graphviz: " + err);
            }
            return;
        }

        if (!pngFile.exists()) {
            jTextArea2.append("\nNo se pudo crear ast.png.");
            return;
        }

        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(pngFile);
                jTextArea2.append("\nImagen AST abierta: " + pngFile.getAbsolutePath());
            } else {
                jTextArea2.append("\nNo se puede abrir la imagen automáticamente.");
            }
        } else {
            jTextArea2.append("\nEl sistema no admite abrir archivos automáticamente.");
        }

    } catch (Exception ex) {
        jTextArea2.append("\nError al generar/mostrar PNG: " + ex.getMessage());
        ex.printStackTrace();
    }
}

private void guardarASTComoDOT(String dotCode) throws IOException {
    File dotFile = new File("ast.dot");
    try (FileWriter fw = new FileWriter(dotFile)) {
        fw.write(dotCode);
    }
    jTextArea2.append("\n\nAST guardado en: " + dotFile.getAbsolutePath());
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interprete().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
